---
title: "Practice Markdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
if (!exists("rawdata")){
    rawdata <- read.csv("activity.csv")
}
```
```{r}
data <- aggregate(steps ~ date, data=rawdata, sum, na.rm = TRUE)
hist(data$steps, breaks=20, main="Total Steps per Day", xlab="Steps", ylab="Frequency")
```

Mean total number of steps taken per day
```{r}
rawsteps_mean <- mean(rawdata$steps, na.rm=TRUE)
rawsteps_median <- median(rawdata$steps, na.rm=TRUE)
print(paste("The mean steps per day is: ", rawsteps_mean))
print(paste("The median steps per day is: ", rawsteps_median))
```
Average Daily Activity Pattern 

```{r}
stepsdata <- aggregate(steps ~ interval, data=rawdata, mean, na.rm=TRUE)
plot(stepsdata$interval, stepsdata$steps, type="l", main="Average Steps per Five Minute Interval",
     xlab="Interval No.", ylab="steps")
maxsteps <- max(stepsdata$steps)
print(paste("The maximum number of steps in a five minute interval was: ", maxsteps))
```

Imputting Missing Values
```{r}
missingdata <- sum(is.na(rawdata$steps))
print(paste("There are", missingdata, "missing data points."))
betterdata <- rawdata
betterdata$steps[is.na(betterdata$steps)] <- median(rawdata$steps, na.rm=TRUE)
betterdataday <- aggregate(steps ~ date, data=betterdata, sum, na.rm=TRUE)
hist(betterdataday$steps, breaks=20, main="Total Steps per Day \n Adjusted Data",
     xlab="Steps", ylab="Frequency")
bsteps_mean <- mean(betterdata$steps)
bsteps_median <- median(betterdata$steps)
print(paste("The mean is: ", bsteps_mean))
print(paste("The median is: ", bsteps_median))
```

Differences in activity patterns between weekdays and weekends
```{r}
betterdata$date <- as.Date(betterdata$date)
betterdata$dayname <- weekdays(betterdata$date)
betterdata$weekend <- as.factor(ifelse(betterdata$dayname == "Saturday" |
                                 betterdata$dayname == "Sunday", "weekend", "weekday"))
                                 
library(lattice)
plotdata <- aggregate(steps ~ interval + weekend, betterdata, mean)
xyplot(steps ~ interval | factor(weekend), data=plotdata, aspect=1/3, type="l")
```
